[none]
release = true

[standalone]
features = "standalone"
release = true

[cookies]
features = "cookies"
release = true

[standalone.cookies]
features = "standalone,cookies"
release = true

[remote]
features = "remote"
release = true

[standalone.remote]
features = "standalone,remote"
release = true

[cookies.remote]
features = "cookies,remote"
release = true

[standalone.cookies.remote]
features = "standalone,cookies,remote"
release = true

[proxy]
features = "proxy"
release = true

[standalone.proxy]
features = "standalone,proxy"
release = true

[cookies.proxy]
features = "cookies,proxy"
release = true

[standalone.cookies.proxy]
features = "standalone,cookies,proxy"
release = true

[remote.proxy]
features = "remote,proxy"
release = true

[standalone.remote.proxy]
features = "standalone,remote,proxy"
release = true

[cookies.remote.proxy]
features = "cookies,remote,proxy"
release = true

[standalone.cookies.remote.proxy]
features = "standalone,cookies,remote,proxy"
release = true

[record]
features = "record"
release = true

[standalone.record]
features = "standalone,record"
release = true

[cookies.record]
features = "cookies,record"
release = true

[standalone.cookies.record]
features = "standalone,cookies,record"
release = true

[remote.record]
features = "remote,record"
release = true

[standalone.remote.record]
features = "standalone,remote,record"
release = true

[cookies.remote.record]
features = "cookies,remote,record"
release = true

[standalone.cookies.remote.record]
features = "standalone,cookies,remote,record"
release = true

[proxy.record]
features = "proxy,record"
release = true

[standalone.proxy.record]
features = "standalone,proxy,record"
release = true

[cookies.proxy.record]
features = "cookies,proxy,record"
release = true

[standalone.cookies.proxy.record]
features = "standalone,cookies,proxy,record"
release = true

[remote.proxy.record]
features = "remote,proxy,record"
release = true

[standalone.remote.proxy.record]
features = "standalone,remote,proxy,record"
release = true

[cookies.remote.proxy.record]
features = "cookies,remote,proxy,record"
release = true

[standalone.cookies.remote.proxy.record]
features = "standalone,cookies,remote,proxy,record"
release = true

[https]
features = "https"
release = true

[standalone.https]
features = "standalone,https"
release = true

[cookies.https]
features = "cookies,https"
release = true

[standalone.cookies.https]
features = "standalone,cookies,https"
release = true

[remote.https]
features = "remote,https"
release = true

[standalone.remote.https]
features = "standalone,remote,https"
release = true

[cookies.remote.https]
features = "cookies,remote,https"
release = true

[standalone.cookies.remote.https]
features = "standalone,cookies,remote,https"
release = true

[proxy.https]
features = "proxy,https"
release = true

[standalone.proxy.https]
features = "standalone,proxy,https"
release = true

[cookies.proxy.https]
features = "cookies,proxy,https"
release = true

[standalone.cookies.proxy.https]
features = "standalone,cookies,proxy,https"
release = true

[remote.proxy.https]
features = "remote,proxy,https"
release = true

[standalone.remote.proxy.https]
features = "standalone,remote,proxy,https"
release = true

[cookies.remote.proxy.https]
features = "cookies,remote,proxy,https"
release = true

[standalone.cookies.remote.proxy.https]
features = "standalone,cookies,remote,proxy,https"
release = true

[record.https]
features = "record,https"
release = true

[standalone.record.https]
features = "standalone,record,https"
release = true

[cookies.record.https]
features = "cookies,record,https"
release = true

[standalone.cookies.record.https]
features = "standalone,cookies,record,https"
release = true

[remote.record.https]
features = "remote,record,https"
release = true

[standalone.remote.record.https]
features = "standalone,remote,record,https"
release = true

[cookies.remote.record.https]
features = "cookies,remote,record,https"
release = true

[standalone.cookies.remote.record.https]
features = "standalone,cookies,remote,record,https"
release = true

[proxy.record.https]
features = "proxy,record,https"
release = true

[standalone.proxy.record.https]
features = "standalone,proxy,record,https"
release = true

[cookies.proxy.record.https]
features = "cookies,proxy,record,https"
release = true

[standalone.cookies.proxy.record.https]
features = "standalone,cookies,proxy,record,https"
release = true

[remote.proxy.record.https]
features = "remote,proxy,record,https"
release = true

[standalone.remote.proxy.record.https]
features = "standalone,remote,proxy,record,https"
release = true

[cookies.remote.proxy.record.https]
features = "cookies,remote,proxy,record,https"
release = true

[standalone.cookies.remote.proxy.record.https]
features = "standalone,cookies,remote,proxy,record,https"
release = true

[http2]
features = "http2"
release = true

[standalone.http2]
features = "standalone,http2"
release = true

[cookies.http2]
features = "cookies,http2"
release = true

[standalone.cookies.http2]
features = "standalone,cookies,http2"
release = true

[remote.http2]
features = "remote,http2"
release = true

[standalone.remote.http2]
features = "standalone,remote,http2"
release = true

[cookies.remote.http2]
features = "cookies,remote,http2"
release = true

[standalone.cookies.remote.http2]
features = "standalone,cookies,remote,http2"
release = true

[proxy.http2]
features = "proxy,http2"
release = true

[standalone.proxy.http2]
features = "standalone,proxy,http2"
release = true

[cookies.proxy.http2]
features = "cookies,proxy,http2"
release = true

[standalone.cookies.proxy.http2]
features = "standalone,cookies,proxy,http2"
release = true

[remote.proxy.http2]
features = "remote,proxy,http2"
release = true

[standalone.remote.proxy.http2]
features = "standalone,remote,proxy,http2"
release = true

[cookies.remote.proxy.http2]
features = "cookies,remote,proxy,http2"
release = true

[standalone.cookies.remote.proxy.http2]
features = "standalone,cookies,remote,proxy,http2"
release = true

[record.http2]
features = "record,http2"
release = true

[standalone.record.http2]
features = "standalone,record,http2"
release = true

[cookies.record.http2]
features = "cookies,record,http2"
release = true

[standalone.cookies.record.http2]
features = "standalone,cookies,record,http2"
release = true

[remote.record.http2]
features = "remote,record,http2"
release = true

[standalone.remote.record.http2]
features = "standalone,remote,record,http2"
release = true

[cookies.remote.record.http2]
features = "cookies,remote,record,http2"
release = true

[standalone.cookies.remote.record.http2]
features = "standalone,cookies,remote,record,http2"
release = true

[proxy.record.http2]
features = "proxy,record,http2"
release = true

[standalone.proxy.record.http2]
features = "standalone,proxy,record,http2"
release = true

[cookies.proxy.record.http2]
features = "cookies,proxy,record,http2"
release = true

[standalone.cookies.proxy.record.http2]
features = "standalone,cookies,proxy,record,http2"
release = true

[remote.proxy.record.http2]
features = "remote,proxy,record,http2"
release = true

[standalone.remote.proxy.record.http2]
features = "standalone,remote,proxy,record,http2"
release = true

[cookies.remote.proxy.record.http2]
features = "cookies,remote,proxy,record,http2"
release = true

[standalone.cookies.remote.proxy.record.http2]
features = "standalone,cookies,remote,proxy,record,http2"
release = true

[https.http2]
features = "https,http2"
release = true

[standalone.https.http2]
features = "standalone,https,http2"
release = true

[cookies.https.http2]
features = "cookies,https,http2"
release = true

[standalone.cookies.https.http2]
features = "standalone,cookies,https,http2"
release = true

[remote.https.http2]
features = "remote,https,http2"
release = true

[standalone.remote.https.http2]
features = "standalone,remote,https,http2"
release = true

[cookies.remote.https.http2]
features = "cookies,remote,https,http2"
release = true

[standalone.cookies.remote.https.http2]
features = "standalone,cookies,remote,https,http2"
release = true

[proxy.https.http2]
features = "proxy,https,http2"
release = true

[standalone.proxy.https.http2]
features = "standalone,proxy,https,http2"
release = true

[cookies.proxy.https.http2]
features = "cookies,proxy,https,http2"
release = true

[standalone.cookies.proxy.https.http2]
features = "standalone,cookies,proxy,https,http2"
release = true

[remote.proxy.https.http2]
features = "remote,proxy,https,http2"
release = true

[standalone.remote.proxy.https.http2]
features = "standalone,remote,proxy,https,http2"
release = true

[cookies.remote.proxy.https.http2]
features = "cookies,remote,proxy,https,http2"
release = true

[standalone.cookies.remote.proxy.https.http2]
features = "standalone,cookies,remote,proxy,https,http2"
release = true

[record.https.http2]
features = "record,https,http2"
release = true

[standalone.record.https.http2]
features = "standalone,record,https,http2"
release = true

[cookies.record.https.http2]
features = "cookies,record,https,http2"
release = true

[standalone.cookies.record.https.http2]
features = "standalone,cookies,record,https,http2"
release = true

[remote.record.https.http2]
features = "remote,record,https,http2"
release = true

[standalone.remote.record.https.http2]
features = "standalone,remote,record,https,http2"
release = true

[cookies.remote.record.https.http2]
features = "cookies,remote,record,https,http2"
release = true

[standalone.cookies.remote.record.https.http2]
features = "standalone,cookies,remote,record,https,http2"
release = true

[proxy.record.https.http2]
features = "proxy,record,https,http2"
release = true

[standalone.proxy.record.https.http2]
features = "standalone,proxy,record,https,http2"
release = true

[cookies.proxy.record.https.http2]
features = "cookies,proxy,record,https,http2"
release = true

[standalone.cookies.proxy.record.https.http2]
features = "standalone,cookies,proxy,record,https,http2"
release = true

[remote.proxy.record.https.http2]
features = "remote,proxy,record,https,http2"
release = true

[standalone.remote.proxy.record.https.http2]
features = "standalone,remote,proxy,record,https,http2"
release = true

[cookies.remote.proxy.record.https.http2]
features = "cookies,remote,proxy,record,https,http2"
release = true

[standalone.cookies.remote.proxy.record.https.http2]
features = "standalone,cookies,remote,proxy,record,https,http2"
release = true

[report]
out = ["Html", "Xml", "Lcov"]
