on: workflow_dispatch

name: All Features Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  full-test:
    name: full-test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Trust custom CA certificates
        shell: bash
        run: |
          set -e
          cp certs/ca.pem certs/ca.crt
          apt-get update
          apt-get install -y ca-certificates
          cp certs/*.crt /usr/local/share/ca-certificates/ || true
          update-ca-certificates

      - name: Run feature power set test
        run: make test-all-features
