on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version (e.g., 1.2.3)'
        required: true
        default: ''
      latest:
        description: 'latest'
        required: false
        default: 'true'
      push:
        description: 'push'
        required: false
        default: 'false'

name: Docker Release

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (provided version only)
        uses: docker/build-push-action@v6
        if: github.event.inputs.latest != 'true'
        with:
          context: .
          push: ${{ github.event.inputs.push }}
          tags: alexliesenfeld/httpmock:${{ github.event.inputs.version }}
      - name: Build and push (provided version + latest)
        uses: docker/build-push-action@v6
        if: github.event.inputs.latest == 'true'
        with:
          context: .
          push: ${{ github.event.inputs.push }}
          tags: |
            alexliesenfeld/httpmock:${{ github.event.inputs.version }},
            alexliesenfeld/httpmock:latest